export enum EnvVariable {
  DATABASE_URL = 'DATABASE_URL',
  ACCESS_SECRET = 'ACCESS_SECRET',
  COOKIE_SECRET = 'COOKIE_SECRET',
  REFRESH_SECRET = 'REFRESH_SECRET',
  ACCESS_TOKEN_EXPIRY_TIME = 'ACCESS_TOKEN_EXPIRY_TIME',
  REFRESH_TOKEN_EXPIRY_TIME = 'REFRESH_TOKEN_EXPIRY_TIME',
}
