export enum EnvVariableEnum {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  DATABASE_URL = 'DATABASE_URL',
  ACCESS_SECRET = 'ACCESS_SECRET',
  COOKIE_SECRET = 'COOKIE_SECRET',
  REFRESH_SECRET = 'REFRESH_SECRET',
  MIGRATE_TENANTS = 'MIGRATE_TENANTS',
  ACCESS_TOKEN_EXPIRY_TIME = 'ACCESS_TOKEN_EXPIRY_TIME',
  REFRESH_TOKEN_EXPIRY_TIME = 'REFRESH_TOKEN_EXPIRY_TIME',
}

export type EnvVariableT = {
  PORT: number;
  NODE_ENV: string;
  DATABASE_URL: string;
  ACCESS_SECRET: string;
  COOKIE_SECRET: string;
  REFRESH_SECRET: string;
  MIGRATE_TENANTS: boolean;
  ACCESS_TOKEN_EXPIRY_TIME: string;
  REFRESH_TOKEN_EXPIRY_TIME: string;
};
